name: Reusable AutoQA Workflow

on:
  workflow_call:
    inputs:
      prompt:
        description: 'Custom prompt for the AutoQA agent (context + task)'
        required: true
        type: string
      max_turns:
        description: 'Maximum number of turns for the agent'
        required: false
        type: string
        default: '100'
      python_version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.10'
      model:
        description: 'Model to use for agent (gpt-5-pro / claude-3-5-sonnet-20241022)'
        required: false
        type: string
        default: 'gpt-5-pro'
    secrets:
      OPENAI_API_KEY:
        required: false
      ANTHROPIC_API_KEY:
        required: false

jobs:
  run-autoqa:
    runs-on: ubuntu-latest
    env:
      OPENAI_MODEL: ${{ inputs.model }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    steps:
      - name: Checkout AutoQA repository
        uses: actions/checkout@v4
        with:
          repository: HP-Victor/autoqa
          path: autoqa

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
          cache: "pip"

      - name: Install dependencies
        working-directory: autoqa
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AutoQA Agent
        working-directory: autoqa
        env:
          PROMPT: ${{ inputs.prompt }}
          MAX_TURNS: ${{ inputs.max_turns }}
        run: |
          python workflow-entry-point.py

      - name: Upload generated code artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: autoqa-generated-code
          path: autoqa/generated_code/
          retention-days: 7
