name: Reusable AutoQA Workflow

on:
  workflow_call:
    inputs:
      prompt:
        description: 'Custom prompt for the AutoQA agent (context + task)'
        required: true
        type: string
      max_turns:
        description: 'Maximum number of turns for the agent'
        required: false
        type: string
        default: '100'
      python_version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.10'
      model:
        description: 'Model to use for agent (gpt-5-pro / claude-3-5-sonnet-20241022)'
        required: false
        type: string
        default: 'gpt-5-pro'
      target_project_path:
        description: 'Path to target project directory (relative to autoqa working directory)'
        required: false
        type: string
        default: '../template-models'
      framework_lib_paths:
        description: 'Comma-separated paths to framework libraries (relative to autoqa working directory)'
        required: false
        type: string
        default: '../selenium-driver-lib,../selenium-commons-lib'
    secrets:
      OPENAI_API_KEY:
        required: false
      ANTHROPIC_API_KEY:
        required: false

jobs:
  run-autoqa:
    runs-on: ubuntu-latest
    env:
      OPENAI_MODEL: ${{ inputs.model }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      FRAMEWORK_LIB_PATHS: ${{ inputs.framework_lib_paths }}
    steps:
      - name: Checkout AutoQA repository
        uses: actions/checkout@v4
        with:
          repository: HP-Victor/autoqa
          path: autoqa

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
          cache: "pip"

      - name: Install dependencies
        working-directory: autoqa
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AutoQA Agent
        working-directory: autoqa
        env:
          PROMPT: ${{ inputs.prompt }}
          MAX_TURNS: ${{ inputs.max_turns }}
          TARGET_PROJECT_PATH: ${{ inputs.target_project_path || '../template-models' }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: |
          python workflow-entry-point.py

      - name: Upload modified target repository
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: autoqa-modified-repository
          path: ${{ inputs.target_project_path || 'template-models' }}/
          retention-days: 7

      - name: Upload AutoQA execution summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: autoqa-execution-summary
          path: ${{ inputs.target_project_path || 'template-models' }}/AutoQA-Generation-Summary.md
          retention-days: 7
