name: Run AutoQA Agent

on:
  push:
    branches:
      - main

env:
  VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
  VNC_HOST: ${{ secrets.VNC_HOST }}
  VNC_PORT: ${{ secrets.VNC_PORT }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  PYTHON_VERSION: "3.10"

jobs:
  run-autoqa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Run AutoQA Agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          VNC_HOST: ${{ env.VNC_HOST }}
          VNC_PORT: ${{ env.VNC_PORT }}
          VNC_PASSWORD: ${{ env.VNC_PASSWORD }}
          OPENAI_MODEL: ${{ env.OPENAI_MODEL }}
          PROMPT: ${{ github.event.inputs.prompt || 'Open firefox and go to mitchellhynes.com' }}
          MAX_TURNS: ${{ github.event.inputs.max_turns || '100' }}
        run: |
          python workflow-entry-point.py

      - name: Save screenshots
        if: always()
        run: |
          mkdir -p artifacts
          cp -f screenshot_*.png artifacts/ 2>/dev/null || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: artifacts
